In [1]:
import pandas as pd
import os

In [2]:
import os
files = os.listdir('E:/Hydrogen-analysis/data/raw/')
print(files)

['Hydrogen Production Projects Database - September 2025_correction_Feb26.xlsx']

In [3]:
df=pd.read_excel('E:/Hydrogen-analysis/data/raw/Hydrogen Production Projects Database - September 2025_correction_Feb26.xlsx')
print(df.shape)
df.head()

(0, 0)

Empty DataFrame
Columns: []
Index: []

In [4]:
import os
files = os.listdir('E:/Hydrogen-analysis/data/raw/')
print(files)

['IEA_Hydrogen_Projects.xlsx']

In [5]:
df=pd.read_excel('E:/Hydrogen-analysis/data/raw/IEA_Hydrogen_Projects.xlsx')
print(df.shape)
df.head()

(0, 0)

Empty DataFrame
Columns: []
Index: []

In [6]:
print(df.columns.tolist())

[]

In [7]:
xl = pd.ExcelFile('E:/Hydrogen-analysis/data/raw/IEA_Hydrogen_Projects.xlsx')
print(xl.sheet_names)

['Notes', 'Definitions and assumptions', 'Projects', 'References', 'Countries']

In [8]:
df = pd.read_excel('E:/Hydrogen-analysis/data/raw/IEA_Hydrogen_Projects.xlsx', sheet_name='Projects')
print(df.shape)
df.head()

(2627, 35)

,Reference,Project name,Country\n(ISO-3),Date online,Decomission date,Status,Technology,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Announced Size,Normalised capacity,Unnamed: 27,Unnamed: 28,Unnamed: 29,IEA zero-carbon estimated normalised capacity\n[Nm³ H₂/hour],Refs,"Geographical details\nDecimal Degrees\n(Lat. N is positive, Long. E is positive)",Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology Comments,Type of electricity (for electrolysis projects),"If dedicated renewables, type of renewable",...,NaN,MWel,Nm³ H₂/h,kt H2/y,t CO₂ captured/y,NaN,NaN,NaN,NaN,NaN
1,Ref,Project name,Country,Date online,Decomission date,Status,Technology,Technology_details,Technology_electricity,Technology_electricity_details,...,Announced Size,Capacity_MWel,Capacity_Nm³ H₂/h,Capacity_kt H2/y,Capacity_t CO₂ captured/y,IEA zero-carbon estimated normalized capacity ...,References,Location,Latitude,Longitude
2,NaN,Other projects from confidential sources (2000...,NaN,NaN,NaN,Operational,PEM,NaN,NaN,NaN,...,21MW,21,4100,3.2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Other projects from confidential sources (2000...,NaN,NaN,NaN,Operational,ALK,NaN,NaN,NaN,...,141.7MW,300,65000,51,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Other projects from confidential sources (2000...,NaN,NaN,NaN,Operational,Other Electrolysis,Various types,NaN,NaN,...,22MW,22,4800,3.8,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# See all column names
print(df.columns.tolist())

['Reference', 'Project name', 'Country\n(ISO-3)', 'Date online', 'Decomission date', 'Status', 'Technology', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Product', 'End use', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Announced Size', 'Normalised capacity', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'IEA zero-carbon estimated normalised capacity\n[Nm³ H₂/hour]', 'Refs', 'Geographical details\nDecimal Degrees\n(Lat. N is positive, Long. E is positive)', 'Unnamed: 33', 'Unnamed: 34']

In [10]:
# See data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2627 entries, 0 to 2626
Data columns (total 35 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Reference                                                                       2619 non-null   object
 1   Project name                                                                    2626 non-null   str
 2   Country
(ISO-3)                                                                 2619 non-null   str
 3   Date online                                                                     1830 non-null   object
 4   Decomission date                                                                117 non-null    object
 5   Status                                                                          2626 non-null   str
 6   Technology                                                                      2626 non-null   str
 7   Unnamed: 7                                                                      1750 non-null   str
 8   Unnamed: 8                                                                      2342 non-null   str
 9   Unnamed: 9                                                                      1487 non-null   str
 10  Product                                                                         2610 non-null   str
 11  End use                                                                         154 non-null    object
 12  Unnamed: 12                                                                     486 non-null    object
 13  Unnamed: 13                                                                     193 non-null    object
 14  Unnamed: 14                                                                     114 non-null    object
 15  Unnamed: 15                                                                     449 non-null    object
 16  Unnamed: 16                                                                     641 non-null    object
 17  Unnamed: 17                                                                     262 non-null    object
 18  Unnamed: 18                                                                     168 non-null    object
 19  Unnamed: 19                                                                     38 non-null     object
 20  Unnamed: 20                                                                     46 non-null     object
 21  Unnamed: 21                                                                     27 non-null     object
 22  Unnamed: 22                                                                     147 non-null    object
 23  Unnamed: 23                                                                     87 non-null     object
 24  Unnamed: 24                                                                     24 non-null     object
 25  Announced Size                                                                  2400 non-null   str
 26  Normalised capacity                                                             2196 non-null   object
 27  Unnamed: 27                                                                     2311 non-null   object
 28  Unnamed: 28                                                                     2324 non-null   object
 29  Unnamed: 29                                                                     113 non-null    object
 30  IEA zero-carbon estimated normalised capacity
[Nm³ H₂/hour]                     2607 non-null   object
 31  Refs                                                                            2456 non-null   str
 32  Geographical details
Decimal Degrees
(Lat. N is positive, Long. E is positive)  2328 non-null   str
 33  Unnamed: 33                                                                     2326 non-null   object
 34  Unnamed: 34                                                                     2325 non-null   object
dtypes: object(24), str(11)
memory usage: 718.4+ KB

In [11]:
# See how many nulls in each column
df.isnull().sum()

Reference                                                                              8
Project name                                                                           1
Country\n(ISO-3)                                                                       8
Date online                                                                          797
Decomission date                                                                    2510
Status                                                                                 1
Technology                                                                             1
Unnamed: 7                                                                           877
Unnamed: 8                                                                           285
Unnamed: 9                                                                          1140
Product                                                                               17
End use                                                                             2473
Unnamed: 12                                                                         2141
Unnamed: 13                                                                         2434
Unnamed: 14                                                                         2513
Unnamed: 15                                                                         2178
Unnamed: 16                                                                         1986
Unnamed: 17                                                                         2365
Unnamed: 18                                                                         2459
Unnamed: 19                                                                         2589
Unnamed: 20                                                                         2581
Unnamed: 21                                                                         2600
Unnamed: 22                                                                         2480
Unnamed: 23                                                                         2540
Unnamed: 24                                                                         2603
Announced Size                                                                       227
Normalised capacity                                                                  431
Unnamed: 27                                                                          316
Unnamed: 28                                                                          303
Unnamed: 29                                                                         2514
IEA zero-carbon estimated normalised capacity\n[Nm³ H₂/hour]                          20
Refs                                                                                 171
Geographical details\nDecimal Degrees\n(Lat. N is positive, Long. E is positive)     299
Unnamed: 33                                                                          301
Unnamed: 34                                                                          302
dtype: int64

In [12]:
print(f"Total projects: {df.shape[0]}")
print(f"Total columns: {df.shape[1]}")
print(f"\nColumn names:\n{df.columns.tolist()}")

Total projects: 2627
Total columns: 35

Column names:
['Reference', 'Project name', 'Country\n(ISO-3)', 'Date online', 'Decomission date', 'Status', 'Technology', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Product', 'End use', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Announced Size', 'Normalised capacity', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'IEA zero-carbon estimated normalised capacity\n[Nm³ H₂/hour]', 'Refs', 'Geographical details\nDecimal Degrees\n(Lat. N is positive, Long. E is positive)', 'Unnamed: 33', 'Unnamed: 34']

In [13]:
# Keep only named columns
df = df.loc[:, ~df.columns.str.startswith('Unnamed')]

# Rename the messy column names (remove newlines and special characters)
df.columns = df.columns.str.replace('\n', ' ', regex=False)
df.columns = df.columns.str.strip()

print(df.columns.tolist())
print(df.shape)

['Reference', 'Project name', 'Country (ISO-3)', 'Date online', 'Decomission date', 'Status', 'Technology', 'Product', 'End use', 'Announced Size', 'Normalised capacity', 'IEA zero-carbon estimated normalised capacity [Nm³ H₂/hour]', 'Refs', 'Geographical details Decimal Degrees (Lat. N is positive, Long. E is positive)']
(2627, 14)

In [15]:
df = df.rename(columns={
    'Country (ISO-3)' : 'country',  
    'Project name'     : 'project_name',
    'Reference'        : 'reference',
    'Date online'      : 'date_online',
    'Decomission date' : 'decommission_date',
    'Status'           : 'status',
    'Technology'       : 'technology',
    'Product'          : 'product',
    'End use'          : 'end_use',
    'Announced Size'   : 'announced_size',
    'Normalised capacity' : 'capacity_normalized',
    'IEA zero-carbon estimated normalised capacity [Nm³ H₂/hour]' : 'capacity_zerocarbon',
    'Refs'             : 'refs',
    'Geographical details Decimal Degrees (Lat. N is positive, Long. E is positive)' : 'latitude'
})

print(df.columns.tolist())

['reference', 'project_name', 'country', 'date_online', 'decommission_date', 'status', 'technology', 'product', 'end_use', 'announced_size', 'capacity_normalized', 'capacity_zerocarbon', 'refs', 'latitude']

In [16]:
df.isnull().sum()

reference                 8
project_name              1
country                   8
date_online             797
decommission_date      2510
status                    1
technology                1
product                  17
end_use                2473
announced_size          227
capacity_normalized     431
capacity_zerocarbon      20
refs                    171
latitude                299
dtype: int64

In [17]:
print("Status values:\n", df['status'].value_counts())
print("\nTechnology values:\n", df['technology'].value_counts())
print("\nProduct values:\n", df['product'].value_counts())

Status values:
 status
Feasibility study    1014
Concept               733
Operational           385
DEMO                  263
FID/Construction      218
Decommisioned           9
Various                 3
Status                  1
Name: count, dtype: int64

Technology values:
 technology
Other Electrolysis    1510
PEM                    423
ALK                    352
NG w CCUS              136
Biomass                 61
SOEC                    45
Other                   32
AEM                     27
Biomass w CCUS          17
Oil w CCUS              10
Coal w CCUS             10
Technology               1
Electrolysis             1
Other electrolysis       1
Name: count, dtype: int64

Product values:
 product
H2          1817
Ammonia      417
MeOH         165
CH4           92
Synfuels      88
Various       27
LOHC           3
Product        1
Name: count, dtype: int64

In [18]:
# Keep rows that at least have a country and status
df_clean = df.dropna(subset=['country', 'status'])

print(f"Rows before: {len(df)}")
print(f"Rows after:  {len(df_clean)}")

Rows before: 2627
Rows after:  2619

In [19]:
df_clean['date_online'] = pd.to_numeric(df_clean['date_online'], errors='coerce')

# Check the year range we have
print(df_clean['date_online'].describe())

count    1829.000000
mean     2024.481684
std         6.570050
min      1965.000000
25%      2023.000000
50%      2026.000000
75%      2028.000000
max      2043.000000
Name: date_online, dtype: float64

In [22]:
df_clean.to_csv('E:/Hydrogen-analysis/data/processed/hydrogen_clean.csv', index=False)
print("Saved successfully!")
print(f"Final shape: {df_clean.shape}")

OSError: Cannot save file into a non-existent directory: 'E:\Hydrogen-analysis\data\processed'

In [23]:
import os
os.makedirs('E:/Hydrogen-analysis/data/processed', exist_ok=True)
print("Folder ready")

Folder ready

In [24]:
df_clean.to_csv('E:/Hydrogen-analysis/data/processed/hydrogen_clean.csv', index=False)
print("Saved successfully!")
print(f"Final shape: {df_clean.shape}")

Saved successfully!
Final shape: (2619, 14)